services:
    app.mail_automatique_manager:
            class: AppBundle\Manager\EmailAutomatiqueManager
            arguments: ["@doctrine.orm.entity_manager",'AdminBundle\Entity\EmailAutomatique']
            public: true