<?php

namespace AppBundle\Repository;

/**
 * ClientPaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientPaysRepository extends \Doctrine\ORM\EntityRepository
{
}
