<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentByNew($id_news)
    {
        return $this->createQueryBuilder("c")
            ->select("c.id")
            ->addSelect("c.message")
            ->addSelect("DATE_FORMAT(c.createdAt,'%d-%m-%Y') as date_created")
            ->addSelect("DATE_FORMAT(c.createdAt,'%h:%i') as time_created")
            ->addSelect("usr.id as user_id")
            ->addSelect("usr.username as user_name")
            ->addSelect("usr.firstname as user_firstname")

            ->innerJoin("c.user", "usr")
            ->where("c.news =:id_news")
            ->setParameter("id_news", $id_news)
            ->getQuery()->getResult();
    }
}
