<?php

namespace AppBundle\Repository;

/**
 * DossiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossiersRepository extends \Doctrine\ORM\EntityRepository
{
}
