<?php

namespace AppBundle\Repository;

/**
 * FichierHasUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichierHasUserRepository extends \Doctrine\ORM\EntityRepository
{
}
