<?php

namespace AppBundle\Repository;

/**
 * FichiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichiersRepository extends \Doctrine\ORM\EntityRepository
{
}
