<?php

namespace AppBundle\Repository;

/**
 * FileUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileUserRepository extends \Doctrine\ORM\EntityRepository
{
}
