<?php

namespace AppBundle\Repository;

/**
 * FolderUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FolderUserRepository extends \Doctrine\ORM\EntityRepository
{
}
