<?php

namespace AppBundle\Repository;

/**
 * InvitationHasUserRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationHasUserRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
