<?php

namespace AppBundle\Repository;

/**
 * MyRightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyRightRepository extends \Doctrine\ORM\EntityRepository
{
}
