<?php

namespace AppBundle\Repository;

/**
 * NasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NasRepository extends \Doctrine\ORM\EntityRepository
{
}
