<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function getNewsByFolder($id_folder)
    {
        $qb = $this->createQueryBuilder("n")
            ->select("n.id")
            ->addSelect("DATE_FORMAT(n.createdAt,'%d-%m-%Y') as date_created")
            ->addSelect("DATE_FORMAT(n.createdAt,'%h:%i') as time_created")
            ->addSelect("type.id as type_id")
            ->addSelect("type.label as type_label")
            ->addSelect("usr.id as user_id")
            ->addSelect("usr.username as user_name")
            ->addSelect("usr.firstname as user_firstname")
            ->addSelect("n.data as data")
            ->innerJoin("n.folder", "d")
            ->innerJoin("n.type", "type")
            ->innerJoin("n.user", "usr")
            ->where("d.id =:id_folder")
            ->setParameter("id_folder", $id_folder);
        $data = $qb->getQuery()->getResult();
        foreach ($data as $key => $rows) {
            if (isset($rows['data']['id_folder'])) {
                $folder = $this->_em->getRepository("AppBundle:Folder")->find($rows['data']['id_folder']);
                $data[$key]['folder_name'] = $folder->getName();
                $data[$key]['id_folder_created'] = $folder->getId();
            }
            if (isset($rows['data']['file'])) {
                foreach ($rows['data']['file'] as $files) {
                    $file = $this->_em->getRepository("AppBundle:File")->find($files);
                    $data[$key]['files_uploads'][$files] = $file->getName();
                }
            }
            unset($data[$key]['data']);
        }
        return $data;
    }
}
