<?php

namespace AppBundle\Repository;

/**
 * ProjectUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectUserRepository extends \Doctrine\ORM\EntityRepository
{
}
