<?php

namespace AppBundle\Repository;

/**
 * RightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RightRepository extends \Doctrine\ORM\EntityRepository
{
}
