<?php

namespace AppBundle\Repository;

/**
 * TypeI18nRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeI18nRepository extends \Doctrine\ORM\EntityRepository
{
}
