<?php

namespace AppBundle\Repository;

/**
 * UrlMappingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlMappingRepository extends \Doctrine\ORM\EntityRepository
{
}
