<?php

namespace AppBundle\Repository;

/**
 * UserPreferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPreferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
