<?php

namespace AppBundle\Repository;

/**
 * VueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VueRepository extends \Doctrine\ORM\EntityRepository
{
}
