api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

api_:
    resource: "@ApiBundle/Controller/"
    type: annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#NelmioApiDocBundle:
#    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
#    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_user_resetting_reset:
    path: /profile/password/reset/{token}
    defaults: { _controller: ApiBundle:User:reset }
    requirements:
        _method: POST|GET