security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    role_hierarchy:
        ROLE_USER: []
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  false #
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
        main:
            pattern: ^/
            logout: true
            anonymous: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /
        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset/password/send-mail, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile/password/reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/send-grid$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/create, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
        - { path: ^/oauth/v2/auth_login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,  role: IS_AUTHENTICATED_FULLY }


