# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
    app.client_manager:
        class: AppBundle\Manager\ClientManager
        arguments: ["@doctrine.orm.entity_manager", 'ApiBundle\Entity\Client']
        public: true
    app.folder_manager:
        class: AppBundle\Manager\FolderManager
        arguments: [
          "@doctrine.orm.entity_manager",
          'AppBundle\Entity\Folder',
          "@event_dispatcher",
          "@security.token_storage",
          "@app.file_manager",
          "@translator"
          ]
        public: true
    app.file_manager:
        class: AppBundle\Manager\FileManager
        arguments: [
          "@doctrine.orm.entity_manager",
          'AppBundle\Entity\File',
          "@event_dispatcher",
          "@security.token_storage",
          "@app.openstack.objectstore"
          ]
        public: true
    app.invitation_request_manager:
        class: AppBundle\Manager\InvitationRequestManager
        arguments: ["@doctrine.orm.entity_manager", 'AppBundle\Entity\InvitationRequest']
        public: true
    app.folder_user_manager:
        class: AppBundle\Manager\FolderUserManager
        arguments: ["@doctrine.orm.entity_manager", 'AppBundle\Entity\FolderUser']
        public: true
    app.file_user_manager:
        class: AppBundle\Manager\FileUserManager
        arguments: ["@doctrine.orm.entity_manager", 'AppBundle\Entity\FileUser']
        public: true
    app.news_manager:
        class: AppBundle\Manager\NewsManager
        arguments: ["@doctrine.orm.entity_manager", 'AppBundle\Entity\News', "@translator"]
        public: true
    app.comment_manager:
            class: AppBundle\Manager\CommentManager
            arguments: ["@doctrine.orm.entity_manager", 'AppBundle\Entity\Comment', "@event_dispatcher"]
            public: true

    app.mailer:
        class: AppBundle\Services\Mailer
        arguments: ['@service_container','@mailer']
        public: true

    app.folder_log_manager:
        class: AppBundle\Manager\FolderLogManager
        arguments: ["@doctrine.orm.entity_manager", 'AppBundle\Entity\FolderLog']
        public: true

    app.file_log_manager:
        class: AppBundle\Manager\FileLogManager
        arguments: ["@doctrine.orm.entity_manager", 'AppBundle\Entity\FileLog']
        public: true

    app.user_manager:
        class: AppBundle\Manager\UserManager
        arguments: ["@doctrine.orm.entity_manager", 'ApiBundle\Entity\User']
        public: true

    app.event.folder:
        class: AppBundle\EventListener\FolderListener
        arguments: ["@app.folder_log_manager", "@doctrine.orm.entity_manager", "@security.token_storage", "@translator"]
        tags:
            - { name: kernel.event_listener, event: folder.on.lock, method: onLockedFolder}
            - { name: kernel.event_listener, event: folder.on.unlock, method: onUnlockedFolder}
            - { name: kernel.event_listener, event: folder.on.creation, method: onCreateFolder}
            - { name: kernel.event_listener, event: folder.on.rename, method: onRenameFolder}
            - { name: kernel.event_listener, event: folder.on.delete, method: onDeleteFolder}
            - { name: kernel.event_listener, event: folder.on.change_owner, method: onChangeFolderOwner}
            - { name: kernel.event_listener, event: folder.on.crypt, method: onCryptFolder}
            - { name: kernel.event_listener, event: folder.on.decrypt, method: onDeCryptFolder}
            - { name: kernel.event_listener, event: folder.on.move, method: onMoveFolder}
            - { name: kernel.event_listener, event: folder.on.copy, method: onCopyFolder}
    app.event.file:
        class: AppBundle\EventListener\FileListener
        arguments: ["@app.file_log_manager", "@doctrine.orm.entity_manager", "@security.token_storage", "@translator"]
        tags:
            - { name: kernel.event_listener, event: file.on.delete, method: onDeleteFile}
            - { name: kernel.event_listener, event: file.on.change_owner, method: onChangeFileOwner}
            - { name: kernel.event_listener, event: file.on.rename, method: onRenameFile}
            - { name: kernel.event_listener, event: file.on.move, method: onMoveFile}
            - { name: kernel.event_listener, event: file.on.copy, method: onCopyFile}
            - { name: kernel.event_listener, event: file.on.create, method: onCreateFile}

    app.event.comment:
        class: AppBundle\EventListener\CommentListener
        arguments: ["@doctrine.orm.entity_manager", "@app.mailer", "@app.mail_automatique_manager", "@app.user_manager"]
        tags:
            - { name: kernel.event_listener, event: comment.on.create, method: onCreateComment}

    app.user_manager:
        class: ApiBundle\Manager\UserManager
        arguments: ["@doctrine.orm.entity_manager", 'ApiBundle\Entity\User']
        public: true

    app.peramlink:
        class: AppBundle\Services\Permalink
        public: true

    app.url_mapping_manager:
        class: AppBundle\Manager\UrlMappingManager
        arguments: ["@doctrine.orm.entity_manager", 'AppBundle\Entity\UrlMapping']
        public: true
    app.utils:
        class: AppBundle\Services\Utils
        arguments: ['@service_container']
        public: true
    app.sms:
        class: AppBundle\Services\Sms
        arguments: ["@service_container","@doctrine.orm.entity_manager"]
        public: true

    app.openstack.auth:
        class:  AppBundle\Services\OpenStack\Auth
        arguments: [%ovh_openstack%]
        public: true

    app.openstack.objectstore:
        class:  AppBundle\Services\OpenStack\ObjectStore
        arguments: [%ovh_openstack%]
        public: true
