<?php

namespace AdminBundle\Repository;

/**
 * EmailAutomatiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailAutomatiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
